
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.1
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.1",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  provider_id: 'provider_id',
  type_id: 'type_id',
  width: 'width',
  height: 'height',
  position: 'position',
  top: 'top',
  bottom: 'bottom',
  left: 'left',
  right: 'right',
  replay: 'replay',
  enabled: 'enabled',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Ads_bannerScalarFieldEnum = {
  id: 'id',
  ads_id: 'ads_id',
  banner_data: 'banner_data'
};

exports.Prisma.Ads_event_videoScalarFieldEnum = {
  id: 'id',
  ads_id: 'ads_id',
  event_key: 'event_key',
  event_data: 'event_data'
};

exports.Prisma.Ads_playedScalarFieldEnum = {
  id: 'id',
  ads_id: 'ads_id',
  player_id: 'player_id',
  started_at: 'started_at',
  ended_at: 'ended_at'
};

exports.Prisma.Ads_providersScalarFieldEnum = {
  id: 'id',
  key: 'key',
  enabled: 'enabled'
};

exports.Prisma.Ads_typesScalarFieldEnum = {
  id: 'id',
  key: 'key'
};

exports.Prisma.AudioScalarFieldEnum = {
  id: 'id',
  audio_key: 'audio_key',
  files_name: 'files_name',
  config: 'config',
  room_id: 'room_id',
  category_id: 'category_id',
  enabled: 'enabled',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Audio_categoriesScalarFieldEnum = {
  id: 'id',
  category_key: 'category_key',
  category_label: 'category_label',
  enabled: 'enabled',
  single_audio: 'single_audio',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Audio_markersScalarFieldEnum = {
  id: 'id',
  audio_id: 'audio_id',
  marker_key: 'marker_key',
  start: 'start',
  duration: 'duration',
  config: 'config'
};

exports.Prisma.Audio_player_configScalarFieldEnum = {
  id: 'id',
  player_id: 'player_id',
  category_id: 'category_id',
  enabled: 'enabled'
};

exports.Prisma.ChatScalarFieldEnum = {
  id: 'id',
  player_id: 'player_id',
  room_id: 'room_id',
  message: 'message',
  private_player_id: 'private_player_id',
  message_type: 'message_type',
  message_time: 'message_time'
};

exports.Prisma.Chat_message_typesScalarFieldEnum = {
  id: 'id',
  key: 'key',
  show_tab: 'show_tab',
  also_show_in_type: 'also_show_in_type'
};

exports.Prisma.ClanScalarFieldEnum = {
  id: 'id',
  owner_id: 'owner_id',
  name: 'name',
  points: 'points',
  level: 'level',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Clan_levelsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  label: 'label',
  required_experience: 'required_experience'
};

exports.Prisma.Clan_levels_modifiersScalarFieldEnum = {
  id: 'id',
  level_id: 'level_id',
  key: 'key',
  property_key: 'property_key',
  operation: 'operation',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.Clan_membersScalarFieldEnum = {
  id: 'id',
  clan_id: 'clan_id',
  player_id: 'player_id'
};

exports.Prisma.ConfigScalarFieldEnum = {
  id: 'id',
  scope: 'scope',
  path: 'path',
  value: 'value',
  type: 'type'
};

exports.Prisma.Config_typesScalarFieldEnum = {
  id: 'id',
  label: 'label'
};

exports.Prisma.Drops_animationsScalarFieldEnum = {
  id: 'id',
  item_id: 'item_id',
  asset_type: 'asset_type',
  asset_key: 'asset_key',
  file: 'file',
  extra_params: 'extra_params'
};

exports.Prisma.FeaturesScalarFieldEnum = {
  id: 'id',
  code: 'code',
  title: 'title',
  is_enabled: 'is_enabled'
};

exports.Prisma.Items_groupScalarFieldEnum = {
  id: 'id',
  key: 'key',
  label: 'label',
  description: 'description',
  files_name: 'files_name',
  sort: 'sort',
  items_limit: 'items_limit',
  limit_per_item: 'limit_per_item'
};

exports.Prisma.Items_inventoryScalarFieldEnum = {
  id: 'id',
  owner_id: 'owner_id',
  item_id: 'item_id',
  qty: 'qty',
  remaining_uses: 'remaining_uses',
  is_active: 'is_active'
};

exports.Prisma.Items_itemScalarFieldEnum = {
  id: 'id',
  key: 'key',
  type: 'type',
  group_id: 'group_id',
  label: 'label',
  description: 'description',
  qty_limit: 'qty_limit',
  uses_limit: 'uses_limit',
  useTimeOut: 'useTimeOut',
  execTimeOut: 'execTimeOut',
  customData: 'customData',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Items_item_modifiersScalarFieldEnum = {
  id: 'id',
  item_id: 'item_id',
  key: 'key',
  property_key: 'property_key',
  operation: 'operation',
  value: 'value',
  maxProperty: 'maxProperty'
};

exports.Prisma.Items_typesScalarFieldEnum = {
  id: 'id',
  key: 'key'
};

exports.Prisma.LocaleScalarFieldEnum = {
  id: 'id',
  locale: 'locale',
  language_code: 'language_code',
  country_code: 'country_code',
  enabled: 'enabled'
};

exports.Prisma.ObjectsScalarFieldEnum = {
  id: 'id',
  room_id: 'room_id',
  layer_name: 'layer_name',
  tile_index: 'tile_index',
  class_type: 'class_type',
  object_class_key: 'object_class_key',
  client_key: 'client_key',
  title: 'title',
  private_params: 'private_params',
  client_params: 'client_params',
  enabled: 'enabled',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Objects_animationsScalarFieldEnum = {
  id: 'id',
  object_id: 'object_id',
  animationKey: 'animationKey',
  animationData: 'animationData'
};

exports.Prisma.Objects_assetsScalarFieldEnum = {
  object_asset_id: 'object_asset_id',
  object_id: 'object_id',
  asset_type: 'asset_type',
  asset_key: 'asset_key',
  asset_file: 'asset_file',
  extra_params: 'extra_params'
};

exports.Prisma.Objects_items_inventoryScalarFieldEnum = {
  id: 'id',
  owner_id: 'owner_id',
  item_id: 'item_id',
  qty: 'qty',
  remaining_uses: 'remaining_uses',
  is_active: 'is_active'
};

exports.Prisma.Objects_items_requirementsScalarFieldEnum = {
  id: 'id',
  object_id: 'object_id',
  item_key: 'item_key',
  required_item_key: 'required_item_key',
  required_quantity: 'required_quantity',
  auto_remove_requirement: 'auto_remove_requirement'
};

exports.Prisma.Objects_items_rewardsScalarFieldEnum = {
  id: 'id',
  object_id: 'object_id',
  item_key: 'item_key',
  reward_item_key: 'reward_item_key',
  reward_quantity: 'reward_quantity',
  reward_item_is_required: 'reward_item_is_required'
};

exports.Prisma.Objects_skillsScalarFieldEnum = {
  id: 'id',
  object_id: 'object_id',
  skill_id: 'skill_id',
  target_id: 'target_id'
};

exports.Prisma.Objects_statsScalarFieldEnum = {
  id: 'id',
  object_id: 'object_id',
  stat_id: 'stat_id',
  base_value: 'base_value',
  value: 'value'
};

exports.Prisma.Objects_typesScalarFieldEnum = {
  id: 'id',
  key: 'key'
};

exports.Prisma.Operation_typesScalarFieldEnum = {
  id: 'id',
  label: 'label',
  key: 'key'
};

exports.Prisma.PlayersScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  name: 'name',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Players_stateScalarFieldEnum = {
  id: 'id',
  player_id: 'player_id',
  room_id: 'room_id',
  x: 'x',
  y: 'y',
  dir: 'dir'
};

exports.Prisma.Players_statsScalarFieldEnum = {
  id: 'id',
  player_id: 'player_id',
  stat_id: 'stat_id',
  base_value: 'base_value',
  value: 'value'
};

exports.Prisma.RespawnScalarFieldEnum = {
  id: 'id',
  object_id: 'object_id',
  respawn_time: 'respawn_time',
  instances_limit: 'instances_limit',
  layer: 'layer',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.RewardsScalarFieldEnum = {
  id: 'id',
  object_id: 'object_id',
  item_id: 'item_id',
  modifier_id: 'modifier_id',
  experience: 'experience',
  drop_rate: 'drop_rate',
  drop_quantity: 'drop_quantity',
  is_unique: 'is_unique',
  was_given: 'was_given',
  has_drop_body: 'has_drop_body',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Rewards_eventsScalarFieldEnum = {
  id: 'id',
  label: 'label',
  description: 'description',
  handler_key: 'handler_key',
  event_key: 'event_key',
  event_data: 'event_data',
  position: 'position',
  enabled: 'enabled',
  active_from: 'active_from',
  active_to: 'active_to'
};

exports.Prisma.Rewards_events_stateScalarFieldEnum = {
  id: 'id',
  rewards_events_id: 'rewards_events_id',
  player_id: 'player_id',
  state: 'state'
};

exports.Prisma.Rewards_modifiersScalarFieldEnum = {
  id: 'id',
  key: 'key',
  property_key: 'property_key',
  operation: 'operation',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.RoomsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  title: 'title',
  map_filename: 'map_filename',
  scene_images: 'scene_images',
  room_class_key: 'room_class_key',
  server_url: 'server_url',
  customData: 'customData',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Rooms_change_pointsScalarFieldEnum = {
  id: 'id',
  room_id: 'room_id',
  tile_index: 'tile_index',
  next_room_id: 'next_room_id'
};

exports.Prisma.Rooms_return_pointsScalarFieldEnum = {
  id: 'id',
  room_id: 'room_id',
  direction: 'direction',
  x: 'x',
  y: 'y',
  is_default: 'is_default',
  from_room_id: 'from_room_id'
};

exports.Prisma.ScoresScalarFieldEnum = {
  id: 'id',
  player_id: 'player_id',
  total_score: 'total_score',
  players_kills_count: 'players_kills_count',
  npcs_kills_count: 'npcs_kills_count',
  last_player_kill_time: 'last_player_kill_time',
  last_npc_kill_time: 'last_npc_kill_time',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Scores_detailScalarFieldEnum = {
  id: 'id',
  player_id: 'player_id',
  obtained_score: 'obtained_score',
  kill_time: 'kill_time',
  kill_player_id: 'kill_player_id',
  kill_npc_id: 'kill_npc_id'
};

exports.Prisma.Skills_class_level_up_animationsScalarFieldEnum = {
  id: 'id',
  class_path_id: 'class_path_id',
  level_id: 'level_id',
  animationData: 'animationData'
};

exports.Prisma.Skills_class_pathScalarFieldEnum = {
  id: 'id',
  key: 'key',
  label: 'label',
  levels_set_id: 'levels_set_id',
  enabled: 'enabled',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Skills_class_path_level_labelsScalarFieldEnum = {
  id: 'id',
  class_path_id: 'class_path_id',
  level_id: 'level_id',
  label: 'label'
};

exports.Prisma.Skills_class_path_level_skillsScalarFieldEnum = {
  id: 'id',
  class_path_id: 'class_path_id',
  level_id: 'level_id',
  skill_id: 'skill_id'
};

exports.Prisma.Skills_groupsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  label: 'label',
  description: 'description',
  sort: 'sort'
};

exports.Prisma.Skills_levelsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  label: 'label',
  required_experience: 'required_experience',
  level_set_id: 'level_set_id'
};

exports.Prisma.Skills_levels_modifiersScalarFieldEnum = {
  id: 'id',
  level_id: 'level_id',
  key: 'key',
  property_key: 'property_key',
  operation: 'operation',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.Skills_levels_modifiers_conditionsScalarFieldEnum = {
  id: 'id',
  levels_modifier_id: 'levels_modifier_id',
  key: 'key',
  property_key: 'property_key',
  conditional: 'conditional',
  value: 'value'
};

exports.Prisma.Skills_levels_setScalarFieldEnum = {
  id: 'id',
  key: 'key',
  label: 'label',
  autoFillRanges: 'autoFillRanges',
  autoFillExperienceMultiplier: 'autoFillExperienceMultiplier',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Skills_owners_class_pathScalarFieldEnum = {
  id: 'id',
  class_path_id: 'class_path_id',
  owner_id: 'owner_id',
  currentLevel: 'currentLevel',
  currentExp: 'currentExp'
};

exports.Prisma.Skills_skillScalarFieldEnum = {
  id: 'id',
  key: 'key',
  type: 'type',
  label: 'label',
  autoValidation: 'autoValidation',
  skillDelay: 'skillDelay',
  castTime: 'castTime',
  usesLimit: 'usesLimit',
  range: 'range',
  rangeAutomaticValidation: 'rangeAutomaticValidation',
  rangePropertyX: 'rangePropertyX',
  rangePropertyY: 'rangePropertyY',
  rangeTargetPropertyX: 'rangeTargetPropertyX',
  rangeTargetPropertyY: 'rangeTargetPropertyY',
  allowSelfTarget: 'allowSelfTarget',
  criticalChance: 'criticalChance',
  criticalMultiplier: 'criticalMultiplier',
  criticalFixedValue: 'criticalFixedValue',
  customData: 'customData',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Skills_skill_animationsScalarFieldEnum = {
  id: 'id',
  skill_id: 'skill_id',
  key: 'key',
  classKey: 'classKey',
  animationData: 'animationData'
};

exports.Prisma.Skills_skill_attackScalarFieldEnum = {
  id: 'id',
  skill_id: 'skill_id',
  affectedProperty: 'affectedProperty',
  allowEffectBelowZero: 'allowEffectBelowZero',
  hitDamage: 'hitDamage',
  applyDirectDamage: 'applyDirectDamage',
  attackProperties: 'attackProperties',
  defenseProperties: 'defenseProperties',
  aimProperties: 'aimProperties',
  dodgeProperties: 'dodgeProperties',
  dodgeFullEnabled: 'dodgeFullEnabled',
  dodgeOverAimSuccess: 'dodgeOverAimSuccess',
  damageAffected: 'damageAffected',
  criticalAffected: 'criticalAffected'
};

exports.Prisma.Skills_skill_group_relationScalarFieldEnum = {
  id: 'id',
  skill_id: 'skill_id',
  group_id: 'group_id'
};

exports.Prisma.Skills_skill_owner_conditionsScalarFieldEnum = {
  id: 'id',
  skill_id: 'skill_id',
  key: 'key',
  property_key: 'property_key',
  conditional: 'conditional',
  value: 'value'
};

exports.Prisma.Skills_skill_owner_effectsScalarFieldEnum = {
  id: 'id',
  skill_id: 'skill_id',
  key: 'key',
  property_key: 'property_key',
  operation: 'operation',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.Skills_skill_owner_effects_conditionsScalarFieldEnum = {
  id: 'id',
  skill_owner_effect_id: 'skill_owner_effect_id',
  key: 'key',
  property_key: 'property_key',
  conditional: 'conditional',
  value: 'value'
};

exports.Prisma.Skills_skill_physical_dataScalarFieldEnum = {
  id: 'id',
  skill_id: 'skill_id',
  magnitude: 'magnitude',
  objectWidth: 'objectWidth',
  objectHeight: 'objectHeight',
  validateTargetOnHit: 'validateTargetOnHit'
};

exports.Prisma.Skills_skill_target_effectsScalarFieldEnum = {
  id: 'id',
  skill_id: 'skill_id',
  key: 'key',
  property_key: 'property_key',
  operation: 'operation',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.Skills_skill_target_effects_conditionsScalarFieldEnum = {
  id: 'id',
  skill_target_effect_id: 'skill_target_effect_id',
  key: 'key',
  property_key: 'property_key',
  conditional: 'conditional',
  value: 'value'
};

exports.Prisma.Skills_skill_typeScalarFieldEnum = {
  id: 'id',
  key: 'key'
};

exports.Prisma.SnippetsScalarFieldEnum = {
  id: 'id',
  locale_id: 'locale_id',
  key: 'key',
  value: 'value',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.StatsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  label: 'label',
  description: 'description',
  base_value: 'base_value',
  customData: 'customData',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.Target_optionsScalarFieldEnum = {
  id: 'id',
  target_key: 'target_key',
  target_label: 'target_label'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  email: 'email',
  username: 'username',
  password: 'password',
  role_id: 'role_id',
  status: 'status',
  created_at: 'created_at',
  updated_at: 'updated_at',
  played_time: 'played_time',
  login_count: 'login_count'
};

exports.Prisma.Users_localeScalarFieldEnum = {
  id: 'id',
  locale_id: 'locale_id',
  user_id: 'user_id'
};

exports.Prisma.Users_loginScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  login_date: 'login_date',
  logout_date: 'logout_date'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.adsOrderByRelevanceFieldEnum = {
  key: 'key',
  position: 'position'
};

exports.Prisma.ads_bannerOrderByRelevanceFieldEnum = {
  banner_data: 'banner_data'
};

exports.Prisma.ads_event_videoOrderByRelevanceFieldEnum = {
  event_key: 'event_key',
  event_data: 'event_data'
};

exports.Prisma.ads_providersOrderByRelevanceFieldEnum = {
  key: 'key'
};

exports.Prisma.ads_typesOrderByRelevanceFieldEnum = {
  key: 'key'
};

exports.Prisma.audioOrderByRelevanceFieldEnum = {
  audio_key: 'audio_key',
  files_name: 'files_name',
  config: 'config'
};

exports.Prisma.audio_categoriesOrderByRelevanceFieldEnum = {
  category_key: 'category_key',
  category_label: 'category_label'
};

exports.Prisma.audio_markersOrderByRelevanceFieldEnum = {
  marker_key: 'marker_key',
  config: 'config'
};

exports.Prisma.chatOrderByRelevanceFieldEnum = {
  message: 'message'
};

exports.Prisma.chat_message_typesOrderByRelevanceFieldEnum = {
  key: 'key'
};

exports.Prisma.clanOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.clan_levelsOrderByRelevanceFieldEnum = {
  label: 'label'
};

exports.Prisma.clan_levels_modifiersOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.configOrderByRelevanceFieldEnum = {
  scope: 'scope',
  path: 'path',
  value: 'value'
};

exports.Prisma.config_typesOrderByRelevanceFieldEnum = {
  label: 'label'
};

exports.Prisma.drops_animationsOrderByRelevanceFieldEnum = {
  asset_type: 'asset_type',
  asset_key: 'asset_key',
  file: 'file',
  extra_params: 'extra_params'
};

exports.Prisma.featuresOrderByRelevanceFieldEnum = {
  code: 'code',
  title: 'title'
};

exports.Prisma.items_groupOrderByRelevanceFieldEnum = {
  key: 'key',
  label: 'label',
  description: 'description',
  files_name: 'files_name'
};

exports.Prisma.items_itemOrderByRelevanceFieldEnum = {
  key: 'key',
  label: 'label',
  description: 'description',
  customData: 'customData'
};

exports.Prisma.items_item_modifiersOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value',
  maxProperty: 'maxProperty'
};

exports.Prisma.items_typesOrderByRelevanceFieldEnum = {
  key: 'key'
};

exports.Prisma.localeOrderByRelevanceFieldEnum = {
  locale: 'locale',
  language_code: 'language_code',
  country_code: 'country_code'
};

exports.Prisma.objectsOrderByRelevanceFieldEnum = {
  layer_name: 'layer_name',
  object_class_key: 'object_class_key',
  client_key: 'client_key',
  title: 'title',
  private_params: 'private_params',
  client_params: 'client_params'
};

exports.Prisma.objects_animationsOrderByRelevanceFieldEnum = {
  animationKey: 'animationKey',
  animationData: 'animationData'
};

exports.Prisma.objects_assetsOrderByRelevanceFieldEnum = {
  asset_type: 'asset_type',
  asset_key: 'asset_key',
  asset_file: 'asset_file',
  extra_params: 'extra_params'
};

exports.Prisma.objects_items_requirementsOrderByRelevanceFieldEnum = {
  item_key: 'item_key',
  required_item_key: 'required_item_key'
};

exports.Prisma.objects_items_rewardsOrderByRelevanceFieldEnum = {
  item_key: 'item_key',
  reward_item_key: 'reward_item_key'
};

exports.Prisma.objects_typesOrderByRelevanceFieldEnum = {
  key: 'key'
};

exports.Prisma.operation_typesOrderByRelevanceFieldEnum = {
  label: 'label'
};

exports.Prisma.playersOrderByRelevanceFieldEnum = {
  name: 'name'
};

exports.Prisma.players_stateOrderByRelevanceFieldEnum = {
  dir: 'dir'
};

exports.Prisma.respawnOrderByRelevanceFieldEnum = {
  layer: 'layer'
};

exports.Prisma.rewards_eventsOrderByRelevanceFieldEnum = {
  label: 'label',
  description: 'description',
  handler_key: 'handler_key',
  event_key: 'event_key',
  event_data: 'event_data'
};

exports.Prisma.rewards_events_stateOrderByRelevanceFieldEnum = {
  state: 'state'
};

exports.Prisma.rewards_modifiersOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.roomsOrderByRelevanceFieldEnum = {
  name: 'name',
  title: 'title',
  map_filename: 'map_filename',
  scene_images: 'scene_images',
  room_class_key: 'room_class_key',
  server_url: 'server_url',
  customData: 'customData'
};

exports.Prisma.rooms_return_pointsOrderByRelevanceFieldEnum = {
  direction: 'direction'
};

exports.Prisma.skills_class_level_up_animationsOrderByRelevanceFieldEnum = {
  animationData: 'animationData'
};

exports.Prisma.skills_class_pathOrderByRelevanceFieldEnum = {
  key: 'key',
  label: 'label'
};

exports.Prisma.skills_class_path_level_labelsOrderByRelevanceFieldEnum = {
  label: 'label'
};

exports.Prisma.skills_groupsOrderByRelevanceFieldEnum = {
  key: 'key',
  label: 'label',
  description: 'description'
};

exports.Prisma.skills_levelsOrderByRelevanceFieldEnum = {
  label: 'label'
};

exports.Prisma.skills_levels_modifiersOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.skills_levels_modifiers_conditionsOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value'
};

exports.Prisma.skills_levels_setOrderByRelevanceFieldEnum = {
  key: 'key',
  label: 'label'
};

exports.Prisma.skills_skillOrderByRelevanceFieldEnum = {
  key: 'key',
  label: 'label',
  rangePropertyX: 'rangePropertyX',
  rangePropertyY: 'rangePropertyY',
  rangeTargetPropertyX: 'rangeTargetPropertyX',
  rangeTargetPropertyY: 'rangeTargetPropertyY',
  customData: 'customData'
};

exports.Prisma.skills_skill_animationsOrderByRelevanceFieldEnum = {
  key: 'key',
  classKey: 'classKey',
  animationData: 'animationData'
};

exports.Prisma.skills_skill_attackOrderByRelevanceFieldEnum = {
  affectedProperty: 'affectedProperty',
  attackProperties: 'attackProperties',
  defenseProperties: 'defenseProperties',
  aimProperties: 'aimProperties',
  dodgeProperties: 'dodgeProperties'
};

exports.Prisma.skills_skill_owner_conditionsOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value'
};

exports.Prisma.skills_skill_owner_effectsOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.skills_skill_owner_effects_conditionsOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value'
};

exports.Prisma.skills_skill_target_effectsOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value',
  minValue: 'minValue',
  maxValue: 'maxValue',
  minProperty: 'minProperty',
  maxProperty: 'maxProperty'
};

exports.Prisma.skills_skill_target_effects_conditionsOrderByRelevanceFieldEnum = {
  key: 'key',
  property_key: 'property_key',
  value: 'value'
};

exports.Prisma.skills_skill_typeOrderByRelevanceFieldEnum = {
  key: 'key'
};

exports.Prisma.snippetsOrderByRelevanceFieldEnum = {
  key: 'key',
  value: 'value'
};

exports.Prisma.statsOrderByRelevanceFieldEnum = {
  key: 'key',
  label: 'label',
  description: 'description',
  customData: 'customData'
};

exports.Prisma.target_optionsOrderByRelevanceFieldEnum = {
  target_key: 'target_key',
  target_label: 'target_label'
};

exports.Prisma.usersOrderByRelevanceFieldEnum = {
  email: 'email',
  username: 'username',
  password: 'password',
  status: 'status'
};
exports.skills_levels_modifiers_conditions_conditional = exports.$Enums.skills_levels_modifiers_conditions_conditional = {
  eq: 'eq',
  ne: 'ne',
  lt: 'lt',
  gt: 'gt',
  le: 'le',
  ge: 'ge'
};

exports.skills_skill_owner_conditions_conditional = exports.$Enums.skills_skill_owner_conditions_conditional = {
  eq: 'eq',
  ne: 'ne',
  lt: 'lt',
  gt: 'gt',
  le: 'le',
  ge: 'ge'
};

exports.skills_skill_owner_effects_conditions_conditional = exports.$Enums.skills_skill_owner_effects_conditions_conditional = {
  eq: 'eq',
  ne: 'ne',
  lt: 'lt',
  gt: 'gt',
  le: 'le',
  ge: 'ge'
};

exports.skills_skill_target_effects_conditions_conditional = exports.$Enums.skills_skill_target_effects_conditions_conditional = {
  eq: 'eq',
  ne: 'ne',
  lt: 'lt',
  gt: 'gt',
  le: 'le',
  ge: 'ge'
};

exports.Prisma.ModelName = {
  ads: 'ads',
  ads_banner: 'ads_banner',
  ads_event_video: 'ads_event_video',
  ads_played: 'ads_played',
  ads_providers: 'ads_providers',
  ads_types: 'ads_types',
  audio: 'audio',
  audio_categories: 'audio_categories',
  audio_markers: 'audio_markers',
  audio_player_config: 'audio_player_config',
  chat: 'chat',
  chat_message_types: 'chat_message_types',
  clan: 'clan',
  clan_levels: 'clan_levels',
  clan_levels_modifiers: 'clan_levels_modifiers',
  clan_members: 'clan_members',
  config: 'config',
  config_types: 'config_types',
  drops_animations: 'drops_animations',
  features: 'features',
  items_group: 'items_group',
  items_inventory: 'items_inventory',
  items_item: 'items_item',
  items_item_modifiers: 'items_item_modifiers',
  items_types: 'items_types',
  locale: 'locale',
  objects: 'objects',
  objects_animations: 'objects_animations',
  objects_assets: 'objects_assets',
  objects_items_inventory: 'objects_items_inventory',
  objects_items_requirements: 'objects_items_requirements',
  objects_items_rewards: 'objects_items_rewards',
  objects_skills: 'objects_skills',
  objects_stats: 'objects_stats',
  objects_types: 'objects_types',
  operation_types: 'operation_types',
  players: 'players',
  players_state: 'players_state',
  players_stats: 'players_stats',
  respawn: 'respawn',
  rewards: 'rewards',
  rewards_events: 'rewards_events',
  rewards_events_state: 'rewards_events_state',
  rewards_modifiers: 'rewards_modifiers',
  rooms: 'rooms',
  rooms_change_points: 'rooms_change_points',
  rooms_return_points: 'rooms_return_points',
  scores: 'scores',
  scores_detail: 'scores_detail',
  skills_class_level_up_animations: 'skills_class_level_up_animations',
  skills_class_path: 'skills_class_path',
  skills_class_path_level_labels: 'skills_class_path_level_labels',
  skills_class_path_level_skills: 'skills_class_path_level_skills',
  skills_groups: 'skills_groups',
  skills_levels: 'skills_levels',
  skills_levels_modifiers: 'skills_levels_modifiers',
  skills_levels_modifiers_conditions: 'skills_levels_modifiers_conditions',
  skills_levels_set: 'skills_levels_set',
  skills_owners_class_path: 'skills_owners_class_path',
  skills_skill: 'skills_skill',
  skills_skill_animations: 'skills_skill_animations',
  skills_skill_attack: 'skills_skill_attack',
  skills_skill_group_relation: 'skills_skill_group_relation',
  skills_skill_owner_conditions: 'skills_skill_owner_conditions',
  skills_skill_owner_effects: 'skills_skill_owner_effects',
  skills_skill_owner_effects_conditions: 'skills_skill_owner_effects_conditions',
  skills_skill_physical_data: 'skills_skill_physical_data',
  skills_skill_target_effects: 'skills_skill_target_effects',
  skills_skill_target_effects_conditions: 'skills_skill_target_effects_conditions',
  skills_skill_type: 'skills_skill_type',
  snippets: 'snippets',
  stats: 'stats',
  target_options: 'target_options',
  users: 'users',
  users_locale: 'users_locale',
  users_login: 'users_login'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
